name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#      - run: npm ci
#      - run: npm run test-ci
  build:
#    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /home/leo/sites/piou
          remote_host: ${{ secrets.SFTP_HOST }}
          remote_port: ${{ secrets.SFTP_PORT }}
          remote_user: ${{ secrets.SFTP_USERNAME }}
          remote_key: ${{ secrets.SFTP_PRIVATE_KEY }}

